engines:
  grep:
    enabled: true
    config:
      patterns:
        missing docstring:
          pattern: def[^\n:]+\):\n\s+[^"' ]
          annotation: "Missing docstring"
          severity: minor
          categories: Clarity
          content: 
          path_patterns:
            - "tlpy/*.py"
  duplication:
    enabled: true
    config:
      languages:
        python:	
          python_version: 3
  radon: 
    enabled: true

ratings:
  paths:
    - "**.py"
